kuasociados/kuasociados/Controllers/ContactoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using kuasociados.Contract;
using kuasociados.Contract.Models;
using WebMatrix.Data;
using WebMatrix.WebData;

namespace kuasociados.Controllers
{
    public class ContactoController : Controller
    {
        public IUserService userservice { get; set; }
        public IInstitutionService institutionservice { get; set; }


        public ContactoController(IUserService _userservice,
                                 IInstitutionService _institutionservice)
        {
            this.userservice = _userservice;
            this.institutionservice = _institutionservice;
        }

        // GET: Contacto
        public ActionResult Index()
        {
            var institution = this.institutionservice.getInstitutionInfo();
            return View(institution);
        }

        [Authorize(Roles = "Secretary")]
        public ActionResult EditInstitution()
        {
            var institution = this.institutionservice.getInstitutionInfo();
            if (institution == null)
            {
                return HttpNotFound();
            }
            return View(institution);
        }

        [Authorize(Roles = "Secretary")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditInstitution(Institution institution)
        {
            if (ModelState.IsValid)
            {
                this.institutionservice.editInstitutionInfo(institution);
                return RedirectToAction("Index");
            }
            return View(institution);
        }

    }
}

kuasociados/kuasociados/Views/Contacto/EditInstitution.cshtml
@model kuasociados.Contract.Models.Institution

@{
    ViewBag.Title = "EditInstitution";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="edit">
    <div class="row mvxl">
        <div class="col-md-12 text-center">
            <h3>Información de Institución:</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-red">
                    <div class="row">
                        <div class="col-md-offset-4 col-md-4  phm">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label" })
                                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.HorarioAtencion, htmlAttributes: new { @class = "control-label" })
                                @Html.EditorFor(model => model.HorarioAtencion, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.HorarioAtencion, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Tel, htmlAttributes: new { @class = "control-label" })
                                @Html.EditorFor(model => model.Tel, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Tel, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Celular, htmlAttributes: new { @class = "control-label" })
                                @Html.EditorFor(model => model.Celular, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Celular, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Mail, htmlAttributes: new { @class = "control-label" })
                                @Html.EditorFor(model => model.Mail, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Mail, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="row mvm">
                        <div class="col-md-12">
                            <div class="form-group">
                                <div class="col-md-offset-4 col-md-4 text-center">
                                    <a href="@(Url.Action("Index" , "Contacto"))">
                                        <input type="button" value="Cancelar" class="mrs button button--wapasha button--text-thick button--text-upper button--size-s">
                                    </a>
                                    <button class="button button--wapasha button--text-thick button--text-upper button--size-s" type="submit" value="Create">Editar</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>

kuasociados/kuasociados/Views/Contacto/Index.cshtml
@model kuasociados.Contract.Models.Institution
@{
    var isSecretary = Roles.IsUserInRole(WebSecurity.CurrentUserName, "Secretary");
    ViewBag.Title = "Index";
    var mailto = "mailto:" + Model.Mail;
}

<section class="contacto">
    <div class="container">
        <div class="row mvxl">
            <div class="col-md-6">
                <div class="">
                    <form class="form-red" method="post">
                        <h3 class="text-center">Contáctanos</h3>
                        <div class="row mvl">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input id="fname" name="name" type="text" placeholder="Nombre" class="form-control">
                                </div>
                            </div>

                   
          
                            <div class="col-md-6">
                                <div class="form-group">

                                    <input id="lname" name="name" type="text" placeholder="Apellido" class="form-control">
                                </div>
                            </div>
                        </div>
                        <div class="row mvl">
                            <div class="col-md-12">
                                <div class="form-group">

                                    <input id="email" name="email" type="text" placeholder="Email" class="form-control">
                                </div>
                            </div>
                        </div>
                        <div class="row mvl">
                            <div class="col-md-12">
                                <div class="form-group">

                                    <textarea class="form-control" id="message" name="message" placeholder="Ingresa tu mensaje aquí" rows="7"></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="row mvl">
                            <div class="col-md-12 text-center">
                                <div class="form-group">
                                        <button type="submit" class="button button--wapasha button--text-thick button--text-upper button--size-s">Enviar</button>
                                    </div>
                                </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-md-6">
                <div>
                    <div class="panel">
                        <div class="panel-heading">
                            <h3 class="text-center">Nuestra información
                            @if(isSecretary)
                            {
                                <span class="text-right"><a class="btn btn-primary" href="@Url.Action("EditInstitution", "Contacto")"><i class="fa fa-pencil" aria-hidden="true"></i></a></span>
                            }  
                            </h3>
                            <hr>
                        </div>
                        <div class="panel-body text-center">
                            <ul class="contacto_ul">
                                <li>
                                    <i class="fa fa-2x fa-home"></i>
                                    <p class="contacto_ul_p">@Model.Direccion</p>
                                </li>
                                <li>
                                    <i class="fa fa-clock-o" style="font-size: 25px;"></i>
                                    <p class="contacto_ul_p">@Model.HorarioAtencion</p>
                                </li>
                                <li>
                                    <i class="fa fa-2x fa-phone"></i>
                                    <p class="contacto_ul_p">@Model.Tel</p>
                                </li>
                                <li>
                                    <i class="fa fa-3x fa-mobile"></i>
                                    <p>@Model.Celular</p>
                                </li>
                                <li>
                                    <i class="fa fa-2x fa-envelope-o"></i>
                                    <a href="@mailto"><p>@Model.Mail</p></a>
                                </li>
                             </ul>
                            <hr />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>