kuasociados/kuasociados/Controllers/NovedadesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using kuasociados.Contract.Models;
using kuasociados.Contract;
using System.Net;

namespace kuasociados.Controllers
{
    public class NovedadesController : Controller
    {
        public INewsService service;
        public NovedadesController(INewsService service) {
            this.service = service;
        }
    
        // GET: Novedades
        public ActionResult Index()
        {
            var news = new List<NewsModel>();

            news = this.service.getNews();

            return View(news);
        }

        [Authorize(Roles = "Secretary")]
        public ActionResult CreateNovedad()
        {
            return View();
        }

        [Authorize(Roles = "Secretary")]
        [HttpPost]
        public ActionResult CreateNovedad(NewsModel news)
        {
            int newid = this.service.getLastestId() + 1;
            //../ Content / img / background - 10.jpg
            news.Id = newid;

            if (ModelState.IsValid)
            {
                this.service.saveNews(news);
                return RedirectToAction("Index");
            }
            else
            {
                return View(news);
            }
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NewsModel news = this.service.getNewsById(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        [Authorize(Roles = "Secretary")]
        public ActionResult DeleteConfirmed(int id)
        {
            this.service.deleteNews(id);
            return RedirectToAction("Index");
        }

    }
}

kuasociados/kuasociados/Controllers/NuestroStaffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using kuasociados.Contract.Models;
using kuasociados.Contract;
using System.Net;
using WebMatrix.Data;
using WebMatrix.WebData;

namespace kuasociados.Controllers
{
    public class NuestroStaffController : Controller
    {
        public IUserService userservice;
        public ILawyerService lawyerservice;
        public IEmployeeService employeeservice;
        public ISpecialtyService specialtyservice;
        public NuestroStaffController(ILawyerService _lawyerservice,
                                      IEmployeeService _employeeservice,
                                      ISpecialtyService _specialtyservice,
                                      IUserService _userservice)
        {
            this.lawyerservice = _lawyerservice;
            this.employeeservice = _employeeservice;
            this.specialtyservice = _specialtyservice;
            this.userservice = _userservice;
        }

        // GET: NuestroStaff

        public ActionResult Index()
        {
            var employeeslist = this.employeeservice.getEmployees();
            var lawyerslist = this.lawyerservice.getLawyers();

            NuestroStaffModel viewModel = new NuestroStaffModel();
            viewModel.lawyers = lawyerslist;
            viewModel.employees = employeeslist;
            ViewBag.SpecialtyList = this.specialtyservice.getSpecialties();
            return View(viewModel);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult CreateLawyer()
        {
            ViewBag.SpecialtyList = this.specialtyservice.getSpecialties();
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateLawyer(RegisterModel model)
        {
            var roles = (SimpleRoleProvider)System.Web.Security.Roles.Provider;
            var membership = (SimpleMembershipProvider)System.Web.Security.Membership.Provider;

            if (ModelState.IsValid)
            {
                this.lawyerservice.saveLawyer(model);
                int newid = this.userservice.getLastestPersonId();
                WebSecurity.CreateUserAndAccount(model.UserName, model.Password,
                                                 propertyValues: new { IdPerson = newid, });


                roles.AddUsersToRoles(new string[] { model.UserName }, new string[] { "Lawyer" });
                return RedirectToAction("Index", "Home");

            }


            return View(model);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult CreateEmployee()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateEmployee(RegisterModel model)
        {
            var roles = (SimpleRoleProvider)System.Web.Security.Roles.Provider;
            var membership = (SimpleMembershipProvider)System.Web.Security.Membership.Provider;

            if (ModelState.IsValid && model.Job != "")
            {
                this.employeeservice.saveEmployee(model);
                int newid = this.userservice.getLastestPersonId();
                WebSecurity.CreateUserAndAccount(model.UserName, model.Password,
                                                 propertyValues: new { IdPerson = newid, });


                roles.AddUsersToRoles(new string[] { model.UserName }, new string[] { "Employee" });
                return RedirectToAction("Index", "Home");

            }


            return View(model);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult CreateSpecialty()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateSpecialty(Specialty specialty)
        {
            int newid = this.specialtyservice.getLatestId() + 1;
            //../ Content / img / background - 10.jpg
            specialty.Id = newid;

            if (ModelState.IsValid)
            {
                this.specialtyservice.saveSpecialty(specialty);
                return RedirectToAction("Index");
            }
            else
            {
                return View(specialty);
            }
        }
    }
}

kuasociados/kuasociados/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using kuasociados.Contract;
using kuasociados.Contract.Models;
using WebMatrix.Data;
using WebMatrix.WebData;

namespace kuasociados.Controllers
{
    public class ProfileController : Controller
    {
        public IUserService userservice;
        public IClientService clientservice;
        public ILawyerService lawyerservice;
        public INotificationService notificationservice;
        public IStateService stateservice;
        public ICaseService caseservice;
        public IEmployeeService employeeservice;
        public ISpecialtyService specialtyservice;


        public ProfileController(IUserService _userservice,
                                 IClientService _clientservice,
                                 ILawyerService _lawyerservice,
                                 INotificationService _notificationservice,
                                 IStateService _stateservice,
                                 IEmployeeService _employeeservice,
                                 ISpecialtyService _specialtyservice,
                                ICaseService _caseservice) {
            this.userservice = _userservice;
            this.clientservice = _clientservice;
            this.lawyerservice = _lawyerservice;
            this.notificationservice = _notificationservice;
            this.stateservice = _stateservice;
            this.caseservice = _caseservice;
            this.employeeservice = _employeeservice;
            this.specialtyservice = _specialtyservice;
        }

        // GET: MyCases

        public ActionResult EmployeeProfile(int? idemployee)
        {
            int userid = WebSecurity.CurrentUserId;
            Employee employeeforauth = this.userservice.getEmployeebyUserId(userid);
            ViewBag.isauthenticated = employeeforauth.Id;
            if (idemployee != null)
            {              
                var employee = this.employeeservice.getEmployeeById(idemployee);
                return View(employee);
            }
            else
            {

                Employee employee = this.userservice.getEmployeebyUserId(userid);
                return View(employee);
            }
        }

        
        // GET: MyCases
        public ActionResult LawyerProfile(int? idlawyer)
        {
            int userid = WebSecurity.CurrentUserId;
            Lawyer lawyerforauth = this.userservice.getLawyerbyUserId(userid);
            ViewBag.isauthenticated = lawyerforauth.Id;

            if (idlawyer != null)
            {
                var lawyer = this.lawyerservice.getLawyerById(idlawyer);
                return View(lawyer);
            }
            else
            {
                Lawyer lawyer = this.userservice.getLawyerbyUserId(userid);
                return View(lawyer); 
            }
            
        }

        [Authorize(Roles = "Lawyer")]
        public ActionResult EditLawyerProfile(int? idlawyer)
        {
            Lawyer lawyer = this.lawyerservice.getLawyerById(idlawyer);
            ViewBag.SpecialtyList = this.specialtyservice.getSpecialties();
            if (lawyer == null)
            {
                return HttpNotFound();
            }
            return View(lawyer);
        }

        [Authorize(Roles = "Lawyer")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditLawyerProfile(Lawyer lawyer)
        {
            if (ModelState.IsValid)
            {
                this.lawyerservice.editLawyer(lawyer);
                return RedirectToAction("LawyerProfile");
            }
            ViewBag.SpecialtyList = this.specialtyservice.getSpecialties();
            return View(lawyer);
        }


        [Authorize(Roles = "Employee")]
        public ActionResult EditEmployeeProfile(int? idemployee)
        {
            Employee employee = this.employeeservice.getEmployeeById(idemployee);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        [Authorize(Roles = "Employee")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditEmployeeProfile(Employee employee)
        {
            if (ModelState.IsValid)
            {
                this.employeeservice.editEmployee(employee);
                return RedirectToAction("EmployeeProfile");
            }
            return View(employee);
        }

    }
}

kuasociados/kuasociados/Views/NuestroStaff/CreateEmployee.cshtml
@model kuasociados.Contract.Models.RegisterModel

@{
    ViewBag.Title = "CreateEmployee";
}

<section class="registrate">
    <section class="container">
        <div class="row mvxl">
            <div class="col-md-offset-3 col-md-6 ">
                <h3 class="mbl  ">Datos de autenticación:</h3>
                @using (Html.BeginForm("Register", "Account", FormMethod.Post, new { @class = "form-red", role = "form" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary("", new { @class = "text-danger" })
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-12">
                                @Html.LabelFor(m => m.UserName, new { @class = "control-label" })
                                @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-12">
                                @Html.LabelFor(m => m.Password, new { @class = "control-label" })
                                @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-12">
                                @Html.LabelFor(m => m.ConfirmPassword, new { @class = "control-label" })
                                @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <hr class="mvs" />
                            <h3 class="mvs">Datos Personales:</h3>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label" })

                                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger validation" })

                            </div>
                        </div>
                        <div class="col-md-6">

                            <div class="form-group">
                                @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label" })

                                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger validation" })

                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">

                            <div class="form-group">
                                @Html.LabelFor(model => model.Dni, htmlAttributes: new { @class = "control-label " })

                                @Html.EditorFor(model => model.Dni, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Dni, "", new { @class = "text-danger validation" })

                            </div>
                        </div>
                        <div class="col-md-6">

                            <div class="form-group">
                                @Html.LabelFor(model => model.BornDate, htmlAttributes: new { @class = "control-label " })
                                @Html.EditorFor(model => model.BornDate, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.BornDate, "", new { @class = "text-danger validation" })

                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label mbxs" })
                                <span class="control-label">M</span>
                                @Html.RadioButtonFor(model => model.Gender, "M", new { htmlAttributes = new { @class = "form-control" } })
                                <span class="control-label">F</span>
                                @Html.RadioButtonFor(model => model.Gender, "F", new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger validation" })

                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label" })

                                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger validation" })

                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Province, htmlAttributes: new { @class = "control-label" })

                                @Html.EditorFor(model => model.Province, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Province, "", new { @class = "text-danger validation" })

                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Codep, htmlAttributes: new { @class = "control-label" })

                                @Html.EditorFor(model => model.Codep, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Codep, "", new { @class = "text-danger validation" })

                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.ProfileImg, htmlAttributes: new { @class = "control-label" })

                                @Html.EditorFor(model => model.ProfileImg, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.ProfileImg, "", new { @class = "text-danger validation" })

                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">

                            <div class="form-group">
                                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label" })

                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger validation" })

                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.EmailConfirm, htmlAttributes: new { @class = "control-label" })

                                @Html.EditorFor(model => model.EmailConfirm, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.EmailConfirm, "", new { @class = "text-danger validation" })

                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Tel, htmlAttributes: new { @class = "control-label" })

                                @Html.EditorFor(model => model.Tel, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.EmailConfirm, "", new { @class = "text-danger validation" })

                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Job, htmlAttributes: new { @class = "control-label " })

                                @Html.EditorFor(model => model.Job, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Job, "", new { @class = "text-danger validation" })

                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group">
                            <div class="col-md-12 text-center">
                                <input type="submit" class="button  button--wapasha button--text-thick button--text-upper button--size-s" value="Registrate" />
                            </div>
                        </div>
                    </div>

                }

            </div>
        </div>
    </section>
</section>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

kuasociados/kuasociados/Views/NuestroStaff/CreateSpecialty.cshtml
@model kuasociados.Contract.Models.Specialty

@{
    ViewBag.Title = "CreateSpecialty";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="specialty">
    <div class="row mvxl">
        <div class="col-md-12 text-center">
            <h3>Nueva especialdad</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-red">
                    <div class="form-group">
                        @Html.HiddenFor(m => m.Id)
                    </div>
                   
                    <div class="row">
                        <div class="col-md-offset-4 col-md-4 text-center phm">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label" })
                                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="row mvm">
                        <div class="col-md-12">
                            <div class="form-group">
                                <div class="col-md-offset-4 col-md-4 text-center">
                                    <a href="@(Url.Action("Index" , "Novedades"))">
                                        <input type="button" value="Cancelar" class="mrs button button--wapasha button--text-thick button--text-upper button--size-s">
                                    </a>
                                    <button class="button button--wapasha button--text-thick button--text-upper button--size-s" type="submit" value="Create">Crear</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                }
            </div>
        </div>
</section>

kuasociados/kuasociados/Views/NuestroStaff/Index.cshtml
@model kuasociados.Contract.Models.NuestroStaffModel


@{
    var isAdmin = Roles.IsUserInRole(WebSecurity.CurrentUserName, "Admin");
}

@{
    ViewBag.Title = "Index";
}

<section class="nuestrostaff pbl">
    <section class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <h1>Nuestro Staff</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                @if (isAdmin)
                {
                    <div class="row">
                        <div class="col-md-12">
                            <div class="panel admin">
                                <h3 class="mbxs">Admin</h3>
                                <a class="btn btn-success" href="@Url.Action("CreateEmployee", "NuestroStaff")"><i class="fa fa-plus" aria-hidden="true"></i></a><span class="mlxs">Agregar empleado</span>
                            </div>
                        </div>
                    </div>
                }
                else
                {

                }
                <div class="row margin-bottom-2">
                    <div class="col-md-12 text-center">
                        <h3>Empleados</h3>
                    </div>
                </div>
                
                <div class="row">
                    @foreach (var employee in Model.employees)
                    {
                        <div class="col-md-6 margin-bottom">
                            <a href="@Url.Action("EmployeeProfile","Profile", new { idemployee = employee.Id })">
                                <div class="thumbnail text-center">
                                    <img src="@employee.ProfileImg" alt="Abogado" class="img-responsive" />
                                    <p class="caption ">@employee.FirstName @employee.LastName</p>
                                    <p class="caption ">@employee.Job</p>
                                </div>
                            </a>
                        </div>     
                    }
                  
                </div>
            </div>
            <div class="col-md-6">
                @if (isAdmin)
                {
                    <div class="row">
                        <div class="col-md-12">
                            <div class="panel admin">
                                <h3 class="mbxs">Admin</h3>
                                <a class="btn btn-success" href="@Url.Action("CreateLawyer", "NuestroStaff")"><i class="fa fa-plus" aria-hidden="true"></i></a><span class="mlxs">Agregar abogado</span>
                                <a class="btn btn-success" href="@Url.Action("CreateSpecialty", "NuestroStaff")"><i class="fa fa-plus" aria-hidden="true"></i></a><span class="mlxs">Agregar especialidad</span>
                            </div>
                        </div>
                    </div>
                }
                else
                {

                }
                <div class="row mbl">
                    <div class="col-md-12 text-center">
                        <h3>Abogados</h3>
                    </div>
                </div>
              
                <div class="row mvs">
                    <div class="col-md-12">
                        <div class="button-group filter-button-group">
                            <button data-filter="*" class="btn">Mostrar Todos</button>
                            @foreach (var specialty in ViewBag.SpecialtyList)
                            {
                                string specialtyclass = "." + @specialty.Id.ToString();
                                <button data-filter="@specialtyclass" class="btn">@specialty.Description</button>
                            }
                        </div>
                    </div>
                </div>
                
                <div class="row">
                    <div class="grid-isotope">
                        @foreach (var lawyer in Model.lawyers)
                        {
                            foreach (var specialty in ViewBag.SpecialtyList)
                            {
                                if (lawyer.IdSpecialty == specialty.Id)
                                {
                                    <div class="grid-item col-md-6 @specialty.Id.ToString()">
                                        <a href="@Url.Action("LawyerProfile","Profile", new { idlawyer = lawyer.Id })">
                                            <div class="thumbnail text-center">
                                                <img src="@lawyer.ProfileImg" alt="Abogado" class="img-responsive" />
                                                <p class="caption ">@lawyer.FirstName @lawyer.LastName</p>
                                            </div>
                                        </a>
                                    </div>
                               
                                }
                            }
                        }
                    </div>
                </div>
            </div>
        </div>
    </section>
</section>