kuasociados/kuasociados/Controllers/MyCasesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using kuasociados.Contract;
using kuasociados.Contract.Models;
using WebMatrix.Data;
using WebMatrix.WebData;

namespace kuasociados.Controllers
{
    public class MyCasesController : Controller
    {
        public IUserService userservice;
        public IClientService clientservice;
        public ILawyerService lawyerservice;

        public MyCasesController(IUserService _userservice,
                                 IClientService _clientservice,
                                 ILawyerService _lawyerservice) {
            this.userservice = _userservice;
            this.clientservice = _clientservice;
            this.lawyerservice = _lawyerservice;
        }

        // GET: MyCases
        [Authorize(Roles = "Client")]
        public ActionResult ClientCases()
        {
            var userid = WebSecurity.CurrentUserId;
            var client = this.userservice.getClientbyUserId(userid);
            return View(client);
        }

        public ActionResult LawyerCases()
        {
            return View();
        }

        // GET: MyCases/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MyCases/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: MyCases/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: MyCases/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: MyCases/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: MyCases/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

kuasociados/kuasociados/Controllers/NotificationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using kuasociados.Contract;
using kuasociados.Contract.Models;
using WebMatrix.Data;
using WebMatrix.WebData;


namespace kuasociados.Controllers
{
    public class NotificationsController : Controller
    {
        public IUserService userservice { get; set; }
        public INotificationService notificationservice { get; set; }


        public NotificationsController(IUserService _userservice,
                                 INotificationService _notificationservice)
        {
            this.userservice = _userservice;
            this.notificationservice = _notificationservice;
        }
        // GET: Notifications

        [Authorize(Roles = "Lawyer")]
        public ActionResult Index()
        {
            int userid = WebSecurity.CurrentUserId;
            Lawyer lawyer = this.userservice.getLawyerbyUserId(userid);
            var listnotification = this.notificationservice.getActiveNotificationsbyLawyer(lawyer.Id);

            return View(listnotification);
        }

        [Authorize(Roles = "Lawyer")]
        public ActionResult DeactivateNotification(int idnotification)
        {
            this.notificationservice.deactivateNotification(idnotification);
            return RedirectToAction("Index");
        }

    }
}

kuasociados/kuasociados/Controllers/NuestroStaffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using kuasociados.Contract.Models;
using kuasociados.Contract;
using System.Net;
using WebMatrix.Data;
using WebMatrix.WebData;

namespace kuasociados.Controllers
{
    public class NuestroStaffController : Controller
    {
        public IUserService userservice;
        public ILawyerService lawyerservice;
        public IEmployeeService employeeservice;
        public ISpecialtyService specialtyservice;
        public NuestroStaffController(ILawyerService _lawyerservice,
                                      IEmployeeService _employeeservice,
                                      ISpecialtyService _specialtyservice,
                                      IUserService _userservice)
        {
            this.lawyerservice = _lawyerservice;
            this.employeeservice = _employeeservice;
            this.specialtyservice = _specialtyservice;
            this.userservice = _userservice;
        }

        // GET: NuestroStaff

        public ActionResult Index()
        {
            var employeeslist = this.employeeservice.getEmployees();
            var lawyerslist = this.lawyerservice.getLawyers();

            NuestroStaffModel viewModel = new NuestroStaffModel();
            viewModel.lawyers = lawyerslist;
            viewModel.employees = employeeslist;
            ViewBag.SpecialtyList = this.specialtyservice.getSpecialties();
            return View(viewModel);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult CreateLawyer()
        {
            ViewBag.SpecialtyList = this.specialtyservice.getSpecialties();
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateLawyer(RegisterModel model)
        {
            var roles = (SimpleRoleProvider)System.Web.Security.Roles.Provider;
            var membership = (SimpleMembershipProvider)System.Web.Security.Membership.Provider;

            if (ModelState.IsValid)
            {
                this.lawyerservice.saveLawyer(model);
                int newid = this.userservice.getLastestPersonId();
                WebSecurity.CreateUserAndAccount(model.UserName, model.Password,
                                                 propertyValues: new { IdPerson = newid, });


                roles.AddUsersToRoles(new string[] { model.UserName }, new string[] { "Lawyer" });
                return RedirectToAction("Index", "Home");

            }


            return View(model);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult CreateEmployee()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateEmployee(RegisterModel model)
        {
            var roles = (SimpleRoleProvider)System.Web.Security.Roles.Provider;
            var membership = (SimpleMembershipProvider)System.Web.Security.Membership.Provider;

            if (ModelState.IsValid && model.Job != "")
            {
                this.employeeservice.saveEmployee(model);
                int newid = this.userservice.getLastestPersonId();
                WebSecurity.CreateUserAndAccount(model.UserName, model.Password,
                                                 propertyValues: new { IdPerson = newid, });


                roles.AddUsersToRoles(new string[] { model.UserName }, new string[] { "Employee" });
                return RedirectToAction("Index", "Home");

            }


            return View(model);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult CreateSpecialty()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateSpecialty(Specialty specialty)
        {
            int newid = this.specialtyservice.getLatestId() + 1;
            //../ Content / img / background - 10.jpg
            specialty.Id = newid;

            if (ModelState.IsValid)
            {
                this.specialtyservice.saveSpecialty(specialty);
                return RedirectToAction("Index");
            }
            else
            {
                return View(specialty);
            }
        }
    }
}

kuasociados/kuasociados/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using kuasociados.Contract;
using kuasociados.Contract.Models;
using WebMatrix.Data;
using WebMatrix.WebData;

namespace kuasociados.Controllers
{
    public class ProfileController : Controller
    {
        public IUserService userservice;
        public IClientService clientservice;
        public ILawyerService lawyerservice;
        public INotificationService notificationservice;
        public IStateService stateservice;
        public ICaseService caseservice;
        public IEmployeeService employeeservice;
        public ISpecialtyService specialtyservice;


        public ProfileController(IUserService _userservice,
                                 IClientService _clientservice,
                                 ILawyerService _lawyerservice,
                                 INotificationService _notificationservice,
                                 IStateService _stateservice,
                                 IEmployeeService _employeeservice,
                                 ISpecialtyService _specialtyservice,
                                ICaseService _caseservice) {
            this.userservice = _userservice;
            this.clientservice = _clientservice;
            this.lawyerservice = _lawyerservice;
            this.notificationservice = _notificationservice;
            this.stateservice = _stateservice;
            this.caseservice = _caseservice;
            this.employeeservice = _employeeservice;
            this.specialtyservice = _specialtyservice;
        }

        // GET: MyCases

        public ActionResult EmployeeProfile(int? idemployee)
        {
            int userid = WebSecurity.CurrentUserId;
            Employee employeeforauth = this.userservice.getEmployeebyUserId(userid);
            ViewBag.isauthenticated = employeeforauth.Id;
            if (idemployee != null)
            {              
                var employee = this.employeeservice.getEmployeeById(idemployee);
                return View(employee);
            }
            else
            {

                Employee employee = this.userservice.getEmployeebyUserId(userid);
                return View(employee);
            }
        }

        
        // GET: MyCases
        public ActionResult LawyerProfile(int? idlawyer)
        {
            int userid = WebSecurity.CurrentUserId;
            Lawyer lawyerforauth = this.userservice.getLawyerbyUserId(userid);
            ViewBag.isauthenticated = lawyerforauth.Id;

            if (idlawyer != null)
            {
                var lawyer = this.lawyerservice.getLawyerById(idlawyer);
                return View(lawyer);
            }
            else
            {
                Lawyer lawyer = this.userservice.getLawyerbyUserId(userid);
                return View(lawyer); 
            }
            
        }

        [Authorize(Roles = "Lawyer")]
        public ActionResult EditLawyerProfile(int? idlawyer)
        {
            Lawyer lawyer = this.lawyerservice.getLawyerById(idlawyer);
            ViewBag.SpecialtyList = this.specialtyservice.getSpecialties();
            if (lawyer == null)
            {
                return HttpNotFound();
            }
            return View(lawyer);
        }

        [Authorize(Roles = "Lawyer")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditLawyerProfile(Lawyer lawyer)
        {
            if (ModelState.IsValid)
            {
                this.lawyerservice.editLawyer(lawyer);
                return RedirectToAction("LawyerProfile");
            }
            ViewBag.SpecialtyList = this.specialtyservice.getSpecialties();
            return View(lawyer);
        }


        [Authorize(Roles = "Employee")]
        public ActionResult EditEmployeeProfile(int? idemployee)
        {
            Employee employee = this.employeeservice.getEmployeeById(idemployee);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        [Authorize(Roles = "Employee")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditEmployeeProfile(Employee employee)
        {
            if (ModelState.IsValid)
            {
                this.employeeservice.editEmployee(employee);
                return RedirectToAction("EmployeeProfile");
            }
            return View(employee);
        }

    }
}

kuasociados/kuasociados/Controllers/SharedController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using kuasociados.Contract;
using kuasociados.Contract.Models;
using WebMatrix.Data;
using WebMatrix.WebData;


namespace kuasociados.Controllers
{
    public class SharedController : Controller
    {
        public IUserService userservice { get; set; }
        public IClientService clientservice { get; set; }
        public INotificationService notificationservice { get; set; }

        public SharedController(IUserService _userservice,
                                 IClientService _clientservice,
                                 INotificationService _notificationservice )
        {
            this.userservice = _userservice;
            this.clientservice = _clientservice;
            this.notificationservice = _notificationservice;
        }

        // GET: Shared

        public int GetNotifications(int idlawyer)
        {
            var listnotification = this.notificationservice.getActiveNotificationsbyLawyer(idlawyer);
            
            var cantnotification = listnotification.Count();
            if (cantnotification != 0)
            {
                return cantnotification;
            }
            else
            {
                return 0;
            }
        }
    }
}

kuasociados/kuasociados/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
  
    @Styles.Render("~/Content/jquery.fullPage.css")
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/animate.css")
    @Styles.Render("~/Content/owl-carousel.css")
    @Styles.Render("~/Content/Scss/main.min.css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/modernizr")


    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" />
  
</head>
<body>
    @{
        var isLawyer = Roles.IsUserInRole(WebSecurity.CurrentUserName, "Lawyer");
        var isClient = Roles.IsUserInRole(WebSecurity.CurrentUserName, "Client");
        var isEmployee = Roles.IsUserInRole(WebSecurity.CurrentUserName, "Employee");
        if (isLawyer) {
        }
    }
    <div class="navbar navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("K. U. y Asociados", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Novedades", "Index", "Novedades")</li>
                    <li>@Html.ActionLink("Contacto", "Index", "Contacto")</li>
                    <li>@Html.ActionLink("Nuestro Staff", "Index", "NuestroStaff")</li>
                    @if (isLawyer)
                    {
                        <li>@Html.ActionLink("Mis Casos", "LawyerCases", "MyCases")</li>
                        <li>@Html.ActionLink("Mi Perfil", "LawyerProfile", "Profile")</li>
                        <li><a href="@Url.Action("Index","Notifications")"><i class="fa fa-bell"><span class="badge"></span></i></a></li>
                    }
                    @if (isEmployee)
                    {
                        <li>@Html.ActionLink("Mi Perfil", "EmployeeProfile", "Profile")</li>
                    }
                    @if (isClient)
                    {
                        <li>@Html.ActionLink("Mis Casos", "ClientCases", "MyCases")</li>
                    }
                </ul>
                 @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
        @RenderBody()
       
        <footer>
            <div class="container">
                <div class="row mtxl">
                    <div class="col-md-offset-1 col-md-2 col-sm-offset-1 col-sm-2 col-xs-12 plxl prl col-border">
                        <a href= "@(Url.Action("Index" , "Home"))">
                            <img src="~/Content/img/logo.png" alt="KUAsociados-logo" class="img-responsive logo_img">
                            <p class="text-center logo-brand">
                                K. U. y Asociados
                            </p>
                        </a>
                    </div>
                    <div class="col-md-2 col-sm-2 col-xs-12 ptl plxl col-border">
                        <ul>
                            <li class="li_title">Clientes</li>
                            <li class="li_item"><a href="{% url 'informacion:crear_lista' %}">Mis Casos</a></li>
                            <li class="li_item"><a href="@(Url.Action("Index" , "Novedades "))">Novedades</a></li>
                        </ul>
                    </div>
                    <div class="col-md-2 col-sm-2 col-xs-12 ptl plxl col-border">
                        <ul>
                            <li class="li_title">Ayuda</li>
                            <li class="li_item"><a href="">FAQ</a></li>
                            <li class="li_item"><a href="">Cómo funciona</a></li>
                            <li class="li_item"><a href="">¿Quiénes somos?</a></li>
                            <li class="li_item"><a href="@(Url.Action("Index" , "Contacto "))">Contacto</a></li>
                        </ul>
                    </div>
                    <div class="col-md-2 col-sm-2 col-xs-12 ptl plxl">
                        <ul>
                            <li class="li_title">K.U y Asociados</li>
                            <li class="li_item"><a href="">Sucursales</a></li>
                            <li class="li_item"><a href="">Testimonios</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
 

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/jquery.fullPage.min.js")
    @RenderSection("scripts", required: false)
    <script type="text/javascript" src="../../Scripts/classie.js"></script>
    <script src="https://unpkg.com/isotope-layout@3.0/dist/isotope.pkgd.min.js"></script>
    <script type="text/javascript" src="../../Scripts/main.js"></script>    
    <script>
     
       
    </script>
</body>
</html>